#!/bin/bash

#SBATCH -J archaic_recovered_hmmix
#SBATCH -t 20:00:00
#SBATCH -n 1
#SBATCH --mem=20G
#SBATCH -o ./logs/archaic_recovered_hmmix.out
#SBATCH -e ./logs/archaic_recovered_hmmix.err
#SBATCH --mail-user=abigail_kuntzleman@brown.edu
#SBATCH --mail-type=FAIL
#SBATCH --array=1-3

if [ "$SLURM_ARRAY_TASK_ID" -eq 1 ]; then
    python3 get_archaic_recovered_from_hmmix.py '/users/akuntzle/IBD_archaic_shared/data/hmmix_output/hmmix_neanderthal_filtered.csv' 'neanderthal'
elif [ "$SLURM_ARRAY_TASK_ID" -eq 2 ]; then
    python3 get_archaic_recovered_from_hmmix.py '/users/akuntzle/IBD_archaic_shared/data/hmmix_output/hmmix_denisovan_filtered.csv' 'denisovan'
elif [ "$SLURM_ARRAY_TASK_ID" -eq 3 ]; then
    python3 get_archaic_recovered_from_hmmix.py '/users/akuntzle/IBD_archaic_shared/data/hmmix_output/hmmix_filtered.csv' 'all'
fi